[project]
name = "modelproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "django-debug-toolbar>=6.0.0",
    "djangorestframework>=3.16.0",
    "drf-spectacular>=0.28.0",
]
