# Generated by Django 5.2.5 on 2025-08-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupontemplate',
            name='views',
        ),
    ]
