# Generated by Django 5.2.5 on 2025-08-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponbook', '0002_remove_coupontemplate_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_district',
            field=models.ForeignKey(help_text='가게의 법정동 부분까지의 주소입니다. 예) 서울특별시 동대문구 이문동', on_delete=django.db.models.deletion.CASCADE, related_name='place', to='couponbook.legaldistrict'),
        ),
    ]
