# Generated by Django 5.2.5 on 2025-08-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couponbook", "0002_place_owner_alter_coupontemplate_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupontemplate",
            name="place",
            field=models.ForeignKey(
                help_text="해당 쿠폰과 연관된 매장 id입니다.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_templates",
                to="couponbook.place",
            ),
        ),
    ]
