# Generated by Django 5.2.5 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponbook', '0003_alter_place_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.CharField(blank=True, help_text='가게의 태그들입니다. 콤마로 구분해서 입력하세요.', max_length=20, null=True),
        ),
    ]
