# Generated by Django 5.2.5 on 2025-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponbook', '0003_alter_coupontemplate_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=15, help_text='위도입니다. 데이터 저장 시 자동 게산됩니다.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=15, help_text='경도입니다. 데이터 저장 시 자동 계산됩니다.', max_digits=18, null=True),
        ),
    ]
