# Generated by Django 5.2.5 on 2025-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CUSTOMER", "손님"), ("OWNER", "점주")],
                default="CUSTOMER",
                help_text="사용자 역할(CUSTOMER/OWNER)",
                max_length=20,
            ),
        ),
    ]
